apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default

  source:
    repoURL: https://github.com/hansonjohnny/DevSecOps2.git
    targetRevision: main
    path: K8-Files/Backend          # ← where your backend manifests are

  destination:
    server: https://kubernetes.default.svc
    namespace: three-tier             # ← namespace to deploy into

  syncPolicy:
    automated:
      prune: true                   # delete removed resources
      selfHeal: true                # fix manual changes automatically
    syncOptions:
      - CreateNamespace=true