apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"    # ← first
spec:
  project: default

  source:
    repoURL: https://github.com/hansonjohnny/DevSecOps2.git
    targetRevision: main
    path: K8-Files/Config

  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true