apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default

  source:
    repoURL: https://github.com/hansonjohnny/DevSecOps2.git
    targetRevision: main
    path: K8-Files/ingress

  destination:
    server: https://kubernetes.default.svc
    namespace: three-tier             # ← namespace to deploy into

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true